<a href="https://colab.research.google.com/github/pnvijay/PyTorch-1.0/blob/master/Intro_to_PyTorch_and_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Sat Jun 27 07:01:44 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8    30W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
!pip install torch torchvision

In [3]:
import torch
print(torch.__version__)

1.5.1+cu101


In [4]:
import torchvision
print(torchvision.__version__)

0.6.1+cu101


In [5]:
print(torch.cuda.is_available())

True


In [6]:
print(torch.cuda.device_count())

1


In [7]:
print(torch.cuda.current_device())

0


In [8]:
print(torch.cuda.get_device_name())

Tesla K80


In [9]:
x = torch.ones(2,2)
print(x)
print(x.dtype)

tensor([[1., 1.],
        [1., 1.]])
torch.float32


In [10]:
x = torch.rand(size=(2,2),dtype=torch.float64)
print(x,x.dtype)

tensor([[0.4391, 0.9202],
        [0.1786, 0.2227]], dtype=torch.float64) torch.float64


In [11]:
x = x.type(torch.float)
print(x,x.dtype)

tensor([[0.4391, 0.9202],
        [0.1786, 0.2227]]) torch.float32


In [12]:
x = torch.ones(2,2,dtype=torch.int8)

In [13]:
y = x.numpy()
print(y)

[[1 1]
 [1 1]]


In [14]:
y.dtype

dtype('int8')

In [15]:
import numpy as np

In [16]:
y = np.random.rand(2,2)
print(y)

[[0.13535337 0.59324225]
 [0.7416988  0.72912585]]


In [17]:
x = torch.from_numpy(y)

In [18]:
print(x,x.dtype)

tensor([[0.1354, 0.5932],
        [0.7417, 0.7291]], dtype=torch.float64) torch.float64
