### About the Notebook
This note book is to go through PyTorch right from the basics all the way to the advanced stuff. We will start off building a Linear Regression Model from Scratch using PyTorch

Import Torch and Check it's version

In [1]:
import torch
print(torch.__version__)

1.0.1.post2


Let's create the data required for the Linear Model to Predict. We will create a numpy array containing random numbers generated. We will transform it into another value using a linear equation. Since numpy is needed let's import that as well.

In [2]:
import numpy as np

We will need to specify the number of rows and columns needed while generating the random numbers. Even if the number of columns is just one, it still needs to be specified

In [3]:
x = np.random.rand(10,1)

In [4]:
x

array([[0.0101604 ],
       [0.16606206],
       [0.44495272],
       [0.20708329],
       [0.12110844],
       [0.22455227],
       [0.73284502],
       [0.87413208],
       [0.22005854],
       [0.57183497]])

In [5]:
x.shape,x.dtype,type(x)

((10, 1), dtype('float64'), numpy.ndarray)

Generate y from a Linear Equation y=2x+4.5

In [6]:
y = 2*x+5

In [7]:
y

array([[5.0203208 ],
       [5.33212412],
       [5.88990544],
       [5.41416659],
       [5.24221688],
       [5.44910455],
       [6.46569003],
       [6.74826415],
       [5.44011709],
       [6.14366994]])

In [8]:
y.shape,y.dtype,type(y)

((10, 1), dtype('float64'), numpy.ndarray)

### Create the Linear Model
Import the torch.nn module

In [9]:
import torch.nn as nn

Create the linear model using nn.Linear and specify how many features come in and how many is required to be predicted. Here we have three features coming in and three features in y predicted.

Check the weights and bias of the model using model.weights and model.bias

In [10]:
model = nn.Linear(1,1)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[0.7161]], requires_grad=True)
Parameter containing:
tensor([-0.7841], requires_grad=True)


PyTorch has initialised a model above with weights and bias. It has also set them to be ready for gradient descent updation by specifying requires_grad=True

### Create the Dataset and Dataloader

In [11]:
from torch.utils.data import TensorDataset, DataLoader

Convert the numpy array to torch tensors and specify that it is of type float. Else there might be a float vs double expectation error during runtime. Make them into a dataset using TensorDataset. Convert the dataset into loadable batches using Dataloader.

In [12]:
inputs = torch.from_numpy(x).float()
targets = torch.from_numpy(y).float()
ds = TensorDataset(inputs,targets)
dl = DataLoader(ds,batch_size=5,shuffle=True)

### Provide a Loss Function and Optimizer

We will import torch.nn.functional and use the inbuilt mean squared error loss function for the model. For Optimizing the weights using gradient descent, let's use the Stochastic Gradient Descent. To the optimizer, we will pass in the parameters (model.parameters()) that needs to be optimized along with a learning rate.

In [13]:
import torch.nn.functional as F
loss_fn = F.mse_loss
opt = torch.optim.SGD(model.parameters(),lr=0.001)

### Define a Fit Function to run epochs and fit the model

The dataloader will provide the datasets into batches of size equal to barch_size. Each batch will run through the model and the prediction from the model will be evaluated against actual for the loss function. The optimizer will step in and try to miminize the loss using gradient descent (Stochastic Gradient Descent) and update the weight and bias accordingly

In [14]:
def fit(num_epochs,model,loss_fn,opt,dl):
    for i in range(num_epochs):
        for xb,yb in dl:
            y_hat = model(xb)
            loss = loss_fn(y_hat,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (i+1)%100 == 0:
            print('Epoch : {}/{} Loss: {}'.format((i+1),num_epochs,loss.item()))

In [15]:
fit(5000,model,loss_fn,opt,dl)

Epoch : 100/5000 Loss: 15.369386672973633
Epoch : 200/5000 Loss: 6.410043239593506
Epoch : 300/5000 Loss: 2.741968870162964
Epoch : 400/5000 Loss: 1.0552864074707031
Epoch : 500/5000 Loss: 0.4463965594768524
Epoch : 600/5000 Loss: 0.20655648410320282
Epoch : 700/5000 Loss: 0.09484745562076569
Epoch : 800/5000 Loss: 0.03551226109266281
Epoch : 900/5000 Loss: 0.046172868460416794
Epoch : 1000/5000 Loss: 0.026620179414749146
Epoch : 1100/5000 Loss: 0.03581564128398895
Epoch : 1200/5000 Loss: 0.039320603013038635
Epoch : 1300/5000 Loss: 0.017418140545487404
Epoch : 1400/5000 Loss: 0.017309091985225677
Epoch : 1500/5000 Loss: 0.02626747079193592
Epoch : 1600/5000 Loss: 0.022478291764855385
Epoch : 1700/5000 Loss: 0.023599358275532722
Epoch : 1800/5000 Loss: 0.0317561998963356
Epoch : 1900/5000 Loss: 0.013441251590847969
Epoch : 2000/5000 Loss: 0.020413029938936234
Epoch : 2100/5000 Loss: 0.022703321650624275
Epoch : 2200/5000 Loss: 0.015249463729560375
Epoch : 2300/5000 Loss: 0.009372014552

In [16]:
print(model.weight),print(model.bias)

Parameter containing:
tensor([[2.2219]], requires_grad=True)
Parameter containing:
tensor([4.9152], requires_grad=True)


(None, None)